"""Подкорректировал модель +location, +fullname

Revision ID: 372aa1661ce6
Revises: 82f31c745088
Create Date: 2026-01-20 17:23:18.278310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '372aa1661ce6'
down_revision: Union[str, Sequence[str], None] = '82f31c745088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('full_name', sa.String(), nullable=False))
    op.add_column('visits', sa.Column('location', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'location')
    op.drop_column('visits', 'full_name')
    # ### end Alembic commands ###
